enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "https://github.com/inotia00/revanced-patches"
integrations-source = "https:/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "both"
included-patches = "'Change header'"
patcher-args = "-Oheader=Cooler "
